#!/bin/bash
set -e
set -u

mkdir ${prefix}
sed 's/ .*//' ${genome} > genome_processed.fa
gemtools index -i genome_processed.fa \
							 -t ${cpus} \
							 -o ${prefix}/genome_index.gem
gemtools t-index -i ${prefix}/genome_index.gem \
								 -a ${annotation} \
								 -t ${cpus} \
								 -o ${prefix}/transcript_index \
								 -m ${readLength}
rm genome_processed.fa
