#!/bin/bash
set -e
set -u

mkdir ${prefix}
pigz -p ${cpus} -dc ${genome} | sed 's/ .*//' > genome_processed.fa
gemtools index -i genome_processed.fa \
							 -t ${cpus} \
							 -o ${prefix}/genome_index.gem
gemtools t-index -i ${prefix}/genome_index.gem \
								 -a <(pigz -p ${cpus} -dc ${annotation}) \
								 -t ${cpus} \
								 -o ${prefix}/transcript_index \
								 -m ${readLength}
rm genome_processed.fa
