#!/bin/bash
set -e
set -u

mkdir ${prefix}
pigz -p ${cpus} -dc ${annotation} > ${annotation.baseName}
pigz -p ${cpus} -dc ${genome} > ${genome.baseName}
STAR --runThreadN ${cpus} \
		 --runMode genomeGenerate \
		 --genomeDir ${prefix} \
		 --genomeFastaFiles ${genome.baseName} \
		 --sjdbGTFfile ${annotation.baseName} \
		 --sjdbOverhang ${sjOverHang} \
&& rm ${genome.baseName} \
&& rm ${annotation.baseName}
