#!/bin/bash
set -e
set -u

mkdir ${prefix}
STAR --runThreadN ${cpus} \
		 --runMode genomeGenerate \
		 --genomeDir ${prefix} \
		 --genomeFastaFiles ${genome} \
		 --sjdbGTFfile ${annotation} \
		 --sjdbOverhang ${sjOverHang}
