#!/bin/bash
set -e
set -u

mkdir Signal
STAR --runThreadN ${cpus} \
     --runMode inputAlignmentsFromBAM \
     --inputBAMfile ${bam} \
     --outWigType bedGraph \
     --outWigStrand Stranded \
     --outFileNamePrefix ./Signal/

cp ${genomeFai} chrSizes.txt
if [ ! -z "${wigRefPrefix}" ]; then
    sed  -ni '/^${wigRefPrefix}/p' chrSizes.txt Signal/*.bg
fi

bedGraphToBigWig Signal/Signal.UniqueMultiple.str1.out.bg \
                 chrSizes.txt \
                 ${prefix}.UniqueMultiple.minusRaw.bw 
bedGraphToBigWig Signal/Signal.UniqueMultiple.str2.out.bg \
                 chrSizes.txt \
                 ${prefix}.UniqueMultiple.plusRaw.bw 

bedGraphToBigWig Signal/Signal.Unique.str1.out.bg \
                 chrSizes.txt \
                 ${prefix}.Unique.minusRaw.bw
bedGraphToBigWig Signal/Signal.Unique.str2.out.bg \
                 chrSizes.txt \
                 ${prefix}.Unique.plusRaw.bw