#!/bin/bash
set -e
set -u

sambamba markdup -t ${cpus} \
                --sort-buffer-size ${memory} \
                --remove-duplicates \
                 ${bam} \
                 ${prefix}.bam && \
sambamba index ${prefix}.bam