#!/bin/bash -eu
samtools index ${bam}
#export FLUX_MEM=${memory}
flux-capacitor --profile \
               -i ${bam} \ 
               -a ${quantRef} \
               --profile-file ${prefix}_profile.json \
               -m SINGLE_STRANDED \
               --read-strand SENSE
flux-capacitor -i ${bam} \
               -a ${quantRef} \
               --profile-file ${prefix}_profile.json \
               -o ${prefix}.isoforms.gtf \
               -m SINGLE_STRANDED \
               --read-strand SENSE
TrtoGn_RPKM.sh -a ${quantRef} \
               -i ${prefix}.isoforms.gtf \
               -o ${prefix}.genes.gff