#!/bin/bash -eu
samtools index ${bam}
#export FLUX_MEM=${memory}
flux-capacitor --profile \
               -i ${bam} \ 
               -a ${quantRef} \
               --profile-file ${id}${prefix}_profile.json \
               -m PAIRED_STRANDED \
               --read-strand MATE1_SENSE
flux-capacitor -i ${bam} \ 
               -a ${quantRef} \
               --profile-file ${id}${prefix}_profile.json \
               -o ${id}${prefix}.isoforms.gtf \
               -m PAIRED_STRANDED \
               --read-strand MATE1_SENSE
TrtoGn_RPKM.sh -a ${quantRef} \
               -i ${id}${prefix}.isoforms.gtf
               -o ${id}${prefix}.genes.gff