#!/bin/bash -eu
samtools index ${bam}
#export FLUX_MEM=${memory}
flux-capacitor -i ${bam} \
               -a ${annotation} \
               -o ${id}${prefix}.gtf \
               -m SINGLE_STRANDED \
               --read-strand ANTISENSE
TrtoGn_RPKM.sh -a ${annotation} \
               -i ${id}${prefix}.gtf