#!/bin/bash -eu
samtools index ${bam}
#export FLUX_MEM=${memory}
flux-capacitor --profile \
               -i ${bam} \ 
               -a ${annotation} \
               --profile-file ${id}${prefix}_profile.json \
               -m SINGLE_STRANDED \
               --read-strand SENSE
flux-capacitor -i ${bam} \
               -a ${annotation} \
               --profile-file ${id}${prefix}_profile.json \
               -o ${id}${prefix}.isoforms.gtf \
               -m SINGLE_STRANDED \
               --read-strand SENSE
TrtoGn_RPKM.sh -a ${annotation} \
               -i ${id}${prefix}.isoforms.gtf