#!/bin/bash -eu
samtools index ${bam}
#export FLUX_MEM=${memory}
flux-capacitor -i ${bam} \
               -a ${quantRef} \
               -o ${id}${prefix}.isoforms.gtf
TrtoGn_RPKM.sh -a ${quantRef} \
               -i ${id}${prefix}.isoforms.gtf