#!/bin/bash -eu
samtools index ${bam}
#export FLUX_MEM=${memory}
flux-capacitor -i ${bam} \
               -a ${quantRef} \
               -o ${prefix}.isoforms.gtf \
               -m PAIRED_STRANDED \
               --read-strand MATE2_SENSE
TrtoGn_RPKM.sh -a ${quantRef} \
               -i ${prefix}.isoforms.gtf \
               -o ${prefix}.genes.gff