#!/bin/bash
set -e
set -u

samtools sort -@ ${cpus} -m ${sortMemory}M -ni -O sam -T . ${bam} \
  | rsem-calculate-expression --sam \
                          --estimate-rspd  \
                          --calc-ci \
                          --no-bam-output \
                          --seed 12345 \
                          -p ${cpus} \
                          --ci-memory ${memory} \
                          --paired-end \
                          --forward-prob 1 \
                          - \
                          ${quantRef}/RSEMref \
                          ${prefix}

rsem-plot-model ${prefix} ${prefix}.pdf
