#!/bin/bash
set -e
set -u

sambamba sort -t ${cpus} -m ${sortMemory}MB -N -l 0 -o - ${bam} \
  | rsem-calculate-expression --bam \
                          --estimate-rspd  \
                          --calc-ci \
                          --no-bam-output \
                          --seed 12345 \
                          -p ${cpus} \
                          --ci-memory ${ciMemory} \
                          - \
                          ${quantRef}/RSEMref \
                          ${prefix}

rsem-plot-model ${prefix} ${prefix}.pdf
