#!/bin/bash -eu
samtools sort -@ ${cpus} -ni -O bam -T . -o tmp_query_sorted.bam ${bam}

rsem-calculate-expression --bam \
                          --estimate-rspd  \
                          --calc-ci \
                          --no-bam-output \
                          --seed 12345 \
                          -p ${cpus} \
                          --ci-memory ${memory} \
                          --forward-prob 0 \
                          tmp_query_sorted.bam \
                          ${quantRef}/RSEMref \
                          ${id}${prefix}
rm tmp_query_sorted.bam
rsem-plot-model ${id}${prefix} ${id}${prefix}.pdf
