#!/bin/bash
set -e
set -u

mkdir genomeDir
STAR --runThreadN ${cpus} \
	--runMode genomeGenerate \
	--limitGenomeGenerateRAM ${memory} \
	--genomeDir genomeDir \
	--genomeFastaFiles ${genome} \
	--sjdbGTFfile ${annotation} \
	--sjdbOverhang ${sjOverHang}