#!/usr/bin/env bash
set -e
set -u

get_version_log() {
    local FORMAT='* %s [%h]'
    if [ ! -z "${PREV}" ]; then
        VERSION_NUMBER=$(echo $VER | sed 's/^v//')
        echo ''
        echo "## Version ${VERSION_NUMBER} "
        echo ''
        echo -e "$(git log --oneline --format="${FORMAT}" ${VER}...${PREV})"
    fi
}

if [ $# -eq 0 ]; then
    VER=$(git describe --tags --abbrev=0)
    PREV=$(git describe --tags --abbrev=0 ${VER}^)

    get_version_log
else
    for VER in "$@"; do
        PREV=$(git describe --tags --abbrev=0 ${VER}^ 2>/dev/null || true)
        
        get_version_log
    done
fi
