#!/bin/bash -eu
samtools view -h -@ ${cpus} ${bam} \
  | awk 'BEGIN {OFS="\\t"} {if (\$1!~/^@/) {\$2=xor(\$2,0x10)}; print}' \
  | samtools view -Sbu - \
  | tee >(
      genomeCoverageBed -strand + -split -bg -ibam - \
      > ${prefix}.contigs.plusRaw.bedgraph
    ) \
  | genomeCoverageBed -strand - -split -bg -ibam - \
> ${prefix}.contigs.minusRaw.bedgraph

contigsNew.py --chrFile ${genomeFai} \
              --fileP ${prefix}.plusRaw.bedgraph \
              --fileM ${prefix}.minusRaw.bedgraph \
							--sortOut \
							> ${prefix}.bed
