#!/bin/bash -eu
bamtools filter -tag NH:1 -in ${bam} -out tmp_unique.bam
genomeCoverageBed -strand + -split -bg -ibam tmp_unique.bam > ${prefix}.plusRaw.bedgraph
genomeCoverageBed -strand - -split -bg -ibam tmp_unique.bam > ${prefix}.minusRaw.bedgraph
rm tmp_unique.bam

contigsNew.py --chrFile ${genomeFai} \
              --fileP ${prefix}.plusRaw.bedgraph \
              --fileM ${prefix}.minusRaw.bedgraph | \
awk '{s=""; for(i=1; i<=NF; i++){s=(s)(\$i)("\\t")} print s}' > ${prefix}.bed