#!/bin/bash -eu
bamtools filter -tag NH:1 -in ${bam} -out tmp.bam && mv -f tmp.bam ${bam}
genomeCoverageBed -strand + -split -bg -ibam ${bam} > ${id}.plusRaw.bedgraph
genomeCoverageBed -strand - -split -bg -ibam ${bam} > ${id}.minusRaw.bedgraph
bedGraphToBigWig ${id}.plusRaw.bedgraph ${genomeFai} ${id}.plusRaw.bw
bedGraphToBigWig ${id}.minusRaw.bedgraph ${genomeFai} ${id}.minusRaw.bw