#!/bin/bash -eu
bamtools filter -tag NH:1 -in ${bam} -out tmp.bam && mv -f tmp.bam ${bam}
genomeCoverageBed -split -bg -ibam ${bam} > ${id}.raw.bedgraph
bedGraphToBigWig ${id}.raw.bedgraph ${genomeFai} ${id}.raw.bw