#!/bin/bash -eu
samtools view -h -@ ${cpus} ${bam} | \
awk 'BEGIN {OFS="\\t"} {if (\$1!~/^@/) {\$2=xor(\$2,0x10)}; print}' | \
samtools view -@ ${cpus} -Sb - > tmp.bam

genomeCoverageBed -strand + -split -bg -ibam tmp.bam > ${id}.plusRaw.bedgraph
genomeCoverageBed -strand - -split -bg -ibam tmp.bam > ${id}.minusRaw.bedgraph
rm tmp.bam
bedGraphToBigWig ${id}.plusRaw.bedgraph ${genomeFai} ${id}.plusRaw.bw
bedGraphToBigWig ${id}.minusRaw.bedgraph ${genomeFai} ${id}.minusRaw.bw