#!/bin/bash
set -e
set -u

genomeCoverageBed -strand + -split -bg -ibam ${bam} > ${prefix}.plusRaw.bedgraph
genomeCoverageBed -strand - -split -bg -ibam ${bam} > ${prefix}.minusRaw.bedgraph
bedGraphToBigWig ${prefix}.plusRaw.bedgraph ${genomeFai} ${prefix}.plusRaw.bw
bedGraphToBigWig ${prefix}.minusRaw.bedgraph ${genomeFai} ${prefix}.minusRaw.bw