#!/bin/bash -eu
mkdir Signal
STAR --runThreadN ${cpus} \
     --runMode inputAlignmentsFromBAM \
     --inputBAMfile ${bam} \
     --outWigType bedGraph \
     --outWigStrand Unstranded \
     --outFileNamePrefix ./Signal/ \
     --outWigReferencesPrefix ${wigRefPrefix}

bedGraphToBigWig Signal/Signal.UniqueMultiple.str1.out.bg \
                 <(grep '^${wigRefPrefix}' ${genomeFai}) \
                 ${id}.UniqueMultiple.raw.bw 

bedGraphToBigWig Signal/Signal.Unique.str1.out.bg \
                 <(grep '^${wigRefPrefix}' ${genomeFai}) \
                 ${id}.Unique.raw.bw