#!/bin/bash -eu
mkdir Signal
STAR --runThreadN ${cpus} \
     --runMode inputAlignmentsFromBAM \
     --inputBAMfile ${bam} \
     --outWigType bedGraph \
     --outWigStrand Stranded \
     --outFileNamePrefix ./Signal/ \
     --outWigReferencesPrefix ${wigRefPrefix}

bedGraphToBigWig Signal/Signal.UniqueMultiple.str1.out.bg \
                 <(grep '^${wigRefPrefix}' ${genomeFai}) \
                 ${prefix}.UniqueMultiple.plusRaw.bw 
bedGraphToBigWig Signal/Signal.UniqueMultiple.str2.out.bg \
                 <(grep '^${wigRefPrefix}' ${genomeFai}) \
                 ${prefix}.UniqueMultiple.minusRaw.bw 

bedGraphToBigWig Signal/Signal.Unique.str1.out.bg \
                 <(grep '^${wigRefPrefix}' ${genomeFai}) \
                 ${prefix}.Unique.plusRaw.bw
bedGraphToBigWig Signal/Signal.Unique.str2.out.bg \
                 <(grep '^${wigRefPrefix}' ${genomeFai}) \
                 ${prefix}.Unique.minusRaw.bw